### ISSUE TITLE
Support Vanity Numbers

### ISSUE THREAD

**Issue by sshaw** [daddyz/phonelib#102]
Ideally:

```
n = Phonelib.parse("800-44-STERN")
p n.e164 # +18004478376
```

Aside from `#original` not sure how the other methods should act. That aside, a quick look at the code _seems_ like it may just be a matter of adding [a simple conversion](https://gist.github.com/sshaw/29d6f7379771e3b4596e228b626bcf9a) to [`sanitized`](https://github.com/daddyz/phonelib/blob/2186be73fe1d8c1555e11d8a6585371fd5ea9bb9/lib/phonelib/phone.rb#L37). 

What do you think?

This is something that libphonenumber supports, though I haven't dug into how they do it.

**Comment by daddyz** [comment]
@sshaw Implemented in version 0.6.10. Check ```Phonelib.vanity_conversion``` setting. Set to true and it will replace chars by numbers

**Comment by sshaw** [comment]
Great, thanks!
