### ISSUE TITLE
Validation fails for 8 digit indian mobile numbers

### ISSUE THREAD

**Issue by vinaymbegur** [daddyz/phonelib#105]
For India (country code +91) phonelib gem **v.0.6.10** is validating 8 digit mobile number as TRUE but when the same number is tested directly with libphonenumber for ex. from url https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html it shows correctly as FALSE for isValidNumber().

Example:- `Phonelib.valid? "+9183082081" or Phonelib.valid? "+91-83082081"` which validates to true.

Ideally phonelib gem also should return FALSE for the above example with 8 digit numbers?

**Comment by daddyz** [comment]
@vinaymbegur Can you check with master? Should be fixed.

**Comment by vinaymbegur** [comment]
Yes its working fine with master now. Thank you so much @daddyz
