### ISSUE TITLE
getting phone invalid validation error

### ISSUE THREAD

**Issue by nik-007** [daddyz/phonelib#106]
I am using the gem for validating Indian phone numbers and its showing many of numbers invalid while those are a valid number and we cross checked it by contacting them. 
The series starts from 8830xxxxxx  and 7400xxxxxx can you guys please revert me why this is happening.

**Comment by daddyz** [comment]
@nik-007 can you provide version of gem that you are using, and exact code how you are using it.
```ruby
p = Phonelib.parse('8830123456', :in)
p.valid? # => true
```
same for 7400xxxxxx
