### ISSUE TITLE
different results on same function: valid_for_country?

### ISSUE THREAD

**Issue by ngouy** [daddyz/phonelib#107]
I do as in readme:
```ruby
#into my rails console

> my_phone_number = '0251092275'
> phone = Phonelib.parse(my_phone_number);
> phone.valid_for_country? 'FR'
=> false

> Phonelib.valid_for_country? my_phone_number, 'FR'
=> true 
```

Is it the desired behaviour ?

Cheerz

**Comment by kasparsj** [comment]
same question here

**Comment by daddyz** [comment]
@kasparsj Once you are doing ```phone = Phonelib.parse(my_phone_number)``` without specifying a country, gem tries to detect country, check ```phone.country```, it will be different. And if you are calling ```valid_for_country?``` method, it does ```parse(phone, country)```, then gem assumes that number might be national number from specified country. You can specify ```Phonelib.default_country = :fr``` to get the same results.

**Comment by ngouy** [comment]
Then why make `valid_for_country?` an instance method waiting for one param (country iso) ?
I understand what u sayed but it's a bit confusing
