### ISSUE TITLE
Not working correctly for india

### ISSUE THREAD

**Issue by akki91** [daddyz/phonelib#108]
12345 is coming up as valid number of india

 Phonelib.invalid_for_country?("12345", "in")  , it will return false.
However in india it should have basic check for 10 digits.

**Comment by daddyz** [comment]
@akki91 check new version

**Comment by akki91** [comment]
@daddyz thanks.. I will check and let you know... can you publish the change logs ?

**Comment by daddyz** [comment]
I already updated changelog, actually short numbers regex handling was
changed. Previously it was validating regex and then was checking type. Now
regex is handled separately.
