### ISSUE TITLE
country_specifier: doesn't seem to work

### ISSUE THREAD

**Issue by bolom** [daddyz/phonelib#109]
I have tried that

 ` validates :telephone, phone: { possible: true, allow_blank: true, types: [:mobile], country_specifier: -> phone { phone.country.try(:upcase) } }
`

I have got this error

`NoMethodError: undefined method `country' for #<Signer:0x007fd725ddea88>`

**Comment by daddyz** [comment]
@bolom which version are you using and does your object really has country method?

**Comment by Babbz75** [comment]
Not sure if this addressing the same problem I have but I'm having a similar issue where I have Phonelib.default_contrry = "US" in the initializer and trying to use phone.e164 or phone.international and instead of add +1555... it just adds +555...

**Comment by daddyz** [comment]
@Babbz75 can you provide example and version you are using?

**Comment by daddyz** [comment]
@Babbz75 If number that is passed is not valid, gem will try to detect the country.
```ruby
Phonelib.default_country = "US"
Phonelib.parse('5551231234').country # => "BR"
Phonelib.parse('5551231234').valid? # => true
Phonelib.parse('15551231234').valid? # => false

Phonelib.parse('2122231234').country # => "US"
Phonelib.parse('2122231234').valid? # => true
Phonelib.parse('2122231234').international # => "+1 212-223-1234"
```
