### ISSUE TITLE
showing incorrect results 

### ISSUE THREAD

**Issue by nik-007** [daddyz/phonelib#114]
Hey team,
I've updated the phonelib to latest version 0.6.13 and having some issues while validating phone numbers
I am trying with  1234567890 this number but it shouldn't, my default country is "IN" as well as strict_check also enabled.
But here its showing the above number as valid one. and its only checking for 10 digits, when I 've tried many different series starting from 2 to 7 its showing all valid phone numbers. this is so horrible
please do the needful.

thank you

**Comment by daddyz** [comment]
@nik-007 This looks to be a really valid number, check this:
```ruby
p = Phonelib.parse '1234567890', 'IN'
p.country # => "IN"
p.international # => "+91 1234 567 890"
p.type # => :fixed_line
```
however number 234567 is not valid
```ruby
p = Phonelib.parse '234567', 'IN'
p.valid? # => false
p.international # => "+91234567"
```
