### ISSUE TITLE
phone number is invalid, never pass validation

### ISSUE THREAD

**Issue by liulupeng1987** [daddyz/phonelib#120]
Dear sir,
I use below in my ruby application
`validates :attribute, phone: true`

But I find, no matter what format of phone number I enter, I never pass the validation.
for example: in rails console
Phonelib.valid?('+8657487019333') => true
Phonelib.valid?('+8613685853953') => true
But When I signup using  '+8657487019333'  '+8613685853953', both are invalid number.
I don't know why?
I want to know what format of number is valid.

Can you help?

Regards,
Lupeng Liu

**Comment by daddyz** [comment]
Hi @liulupeng1987 ,
What do you have in your initializer in case there is some, which version are you using?
