### ISSUE TITLE
Philippine area codes seems outdated

### ISSUE THREAD

**Issue by rgabriel01** [daddyz/phonelib#121]
Good day,

I tried validating a landline number +63 93 752 1005 and got an invalid response.
93 is a valid Philippine area code. Is the data somewhat outdated? We are using phonelib (0.6.16)

**Comment by daddyz** [comment]
@rgabriel01 thanks for reporting, however according to [wiki](https://en.wikipedia.org/wiki/Telephone_numbers_in_the_Philippines#Mobile_phone_area_codes), mobile phone numbers have format of "+63 (xxx) xxx-xxxx" meaning you are missing one more digit. I am basing validations on google's libphonenumber data, and they are based on wiki.
