### ISSUE TITLE
Egypt new mobile carrier

### ISSUE THREAD

**Issue by HusseinReda** [daddyz/phonelib#123]
Hello,

Egypt recently had a new mobile carrier. Phonelib only accepts numbers starting with (+2012, +2011, +2010) which are for Orange, Etisalat and Vodafone mobile carriers respectively.
The new mobile carrier is WE, which starts with (+2015), which Phonlib doesn't accept for Egypt as valid phone number. The new carrier has the number of digits as the others.

This is pretty urgent in order to use Phonelib in the proper way.
Looking forward to hearing from you soon.

**Comment by HusseinReda** [comment]
The issue with the latest version of the gem.

**Comment by EslamMoh** [comment]
Hello Hussien ,
I'm from Egypt and i'm facing the same problem , and i need to know if you could solve it or not ?
Thanks in advance
