### ISSUE TITLE
Australian mobile format now includes 05

### ISSUE THREAD

**Issue by aldhsu** [daddyz/phonelib#124]
Hi @daddyz, Australia has added the prefix 05 for mobiles (see [Wikipedia](https://en.wikipedia.org/wiki/Telephone_numbers_in_Australia#Mobile_phone_numbers_.2804.2C_05.29)).

**Comment by daddyz** [comment]
@aldhsu Hi, I recently updated the data and tried the phone like this one "61 550 580 000"?
```ruby
Phonelib.parse("61 550 580 000").valid? #  => true
Phonelib.parse("61 550 580 000").international #  => "+61 550 580 000"
```
Is it correct?

**Comment by aldhsu** [comment]
Hi @daddyz thanks for the update. 

I don't think this is working though. It could be because the rules are very recent and not finalized. 
```ruby
Phonelib.parse("61 550 580 000").type # => :voip
```

I noticed this error becuase FFaker started generating 05 numbers, so they could just be ahead of the curve. I hacked around it for now if the rules aren't set yet.

**Comment by daddyz** [comment]
Recent update didn't change anything in this type. I am closing the issue for now.
