### ISSUE TITLE
Large list of timezones gets returned when using .timezone

### ISSUE THREAD

**Issue by mberman84** [daddyz/phonelib#126]
We just upgraded from 0.5.2 to 0.6.17 and timezone parsing seems to have broken for a large percentage of our phone numbers. Previously, when we would do:

`Phonelib.parse(some_number).timezone`

it would return a single timezone.

Now, when we run that same command on the same phone number, it returns a long list of timezones. 

I'm not sure what the intention of this functionality is or if it's just a bug? 

Some phone numbers still return a single timezone but now a bunch return this long list.

**Comment by paulief** [comment]
+1

**Comment by daddyz** [comment]
@paulief @mberman84 Hi, it's not always possible to detect timezone for specific number, in case of small countries, it's ok like:
```ruby
Phonelib.parse('44123123123').timezone # => "Europe/London"
```
But if you are talking about Australian mobile phone number, it can be anywhere in the country, so gem returns list of all possible timezones:
```ruby
Phonelib.parse('6155123123').timezone #  => ["Antarctica/Macquarie", "Australia/Adelaide", "Australia/Eucla", "Australia/Lord_Howe", "Australia/Perth", "Australia/Sydney", "Indian/Christmas", "Indian/Cocos"]
```
However if you are taking some landline in Australia, it will be detected as single timezone:
```ruby
Phonelib.parse('6125123123').timezone #  => "Australia/Sydney"
```
Tell me if it resolves the issue.

**Comment by mberman84** [comment]
@daddyz this is for US-based phone numbers with easily recognizable area codes. Major cities. But apparently before upgrading, when we parsed the same US-based number, it would return a single, incorrect, timezone. Now, for that same number, it returns a large list. 

Putting the area code into google search returns the correct timezone/city.

**Comment by piotrb** [comment]
I'm getting the same issue with the 250 area code .. for example +12501001000, also returns a whole array of time zones .. of basically all of the US/Canada .. 

```ruby
Phonelib.parse("+12501001000").timezone
=> ["America/Anguilla",
 "America/Antigua",
 "America/Barbados",
 "America/Cayman",
 "America/Chicago",
 "America/Denver",
 "America/Dominica",
 "America/Edmonton",
 "America/Grand_Turk",
 "America/Grenada",
 "America/Halifax",
 "America/Jamaica",
 "America/Juneau",
 "America/Los_Angeles",
 "America/Lower_Princes",
 "America/Montserrat",
 "America/Nassau",
 "America/New_York",
 "America/Phoenix",
 "America/Port_of_Spain",
 "America/Puerto_Rico",
 "America/Santo_Domingo",
 "America/St_Johns",
 "America/St_Kitts",
 "America/St_Lucia",
 "America/St_Thomas",
 "America/St_Vincent",
 "America/Toronto",
 "America/Tortola",
 "America/Vancouver",
 "America/Winnipeg",
 "Atlantic/Bermuda",
 "Pacific/Guam",
 "Pacific/Honolulu",
 "Pacific/Pago_Pago",
 "Pacific/Saipan"]
```

Now if you google it .. area code 250 is a split of the usual 604 area code for more rural areas in BC Canada, which should all be the same time zone ..

**Comment by daddyz** [comment]
@piotrb @mberman84 recent data update changed the result, now 250 returns single timezone:
```ruby
Phonelib.parse("+12503061000").timezone # => "America/Vancouver"
```
Hope it helps
