### ISSUE TITLE
does not accept valid Malaysian mobile

### ISSUE THREAD

**Issue by ryan2johnson9** [daddyz/phonelib#129]
Phonelib.valid_for_country? '0184747743', 'MY'

returns false

but apparently should return true

**Comment by ryan2johnson9** [comment]
Looking more closely I see:

`[2] pry(main)> Phonelib.valid_for_country? '0183947743', 'MY' => true`

seems to fail in the range 01840.... through to 01856...

`[56] pry(main)> Phonelib.valid_for_country? '0185747742', 'MY' => true`

[and apparently these are valid U Mobile numbers](https://en.wikipedia.org/wiki/Telephone_numbers_in_Malaysia#Mobile_phone_codes_and_IP_telephony)

**Comment by ryan2johnson9** [comment]
Just adding more data- I added an extra digit to that number and it showed as valid

    ph = ::Phonelib.parse("+60184047743")
    => #<Phonelib::Phone:0x000000075302f8
        @data=
            {"MY"=>
                 {:id=>"MY",
                  :country_code=>"60",
                  :international_prefix=>"00",
                  :national_prefix=>"0",
                  :mobile_number_portable_region=>"true",
                  :national=>"184047743",
                  :format=>{:pattern=>"([18]\\d)(\\d{3})(\\d{3,4})", :national_prefix_formatting_rule=>"$NP$FG", :leading_digits=>"1[02-46-9][1-9]|8", :format=>"$1-$2 $3"},
                  :valid=>[],
                  :possible=>[:fixed_or_mobile]}},
                @extension="",
                @national_number="184047743",
                @original="+60184047743",
                @original_s="+60184047743",
                @sanitized="60184047743">
    ph.valid?
    => false
    
    
    ph = ::Phonelib.parse("+601840477439")
    => #<Phonelib::Phone:0x007fac152eb508
        @data=
            {"MY"=>
                 {:id=>"MY",
                  :country_code=>"60",
                  :international_prefix=>"00",
                  :national_prefix=>"0",
                  :mobile_number_portable_region=>"true",
                  :national=>"1840477439",
                  :format=>{:pattern=>"(\\d+)(\\d{3})(\\d{4})", :format=>"$1 $2 $3"},
                  :valid=>[:mobile],
                  :possible=>[:premium_rate, :toll_free, :voip, :mobile]}},
                @extension="",
                @national_number="1840477439",
                @original="+601840477439",
                @original_s="+601840477439",
                @sanitized="601840477439">
    ph.valid?
    => true

and checking with global_phone gem it says it is valid

    num = GlobalPhone.parse("+60184047743")
    => #<GlobalPhone::Number territory=#<GlobalPhone::Territory country_code=60 name=MY> national_string="184047743">
    num.valid?
    => true

and interstingly, adding an extra digit gives false with global_phone wheras phonelib gives true

    num = GlobalPhone.parse("+601840477439")
    => #<GlobalPhone::Number territory=#<GlobalPhone::Territory country_code=60 name=MY> national_string="1840477439">
    num.valid?
    => false

So if the person who reported this to me, climing it is a valid mobile, has not made a mistake, and if we assume global_phone is accurate, it seems to point to a bug in the pattern formats in Phonelib, namely, from above code

              :format=>{:pattern=>"([18]\\d)(\\d{3})(\\d{3,4})", :national_prefix_formatting_rule=>"$NP$FG", :leading_digits=>"1[02-46-9][1-9]|8", :format=>"$1-$2 $3"},

gives false but should give true and this:

              :format=>{:pattern=>"(\\d+)(\\d{3})(\\d{4})", :format=>"$1 $2 $3"},

gives true but should give false

**Comment by daddyz** [comment]
@ryan2johnson9 The data has been updated, now:
```ruby
Phonelib.valid_for_country? '0184747743', 'MY' # => true
```
Check against 0.6.19.

**Comment by ryan2johnson9** [comment]
Thanks! Have not tested yet, I went to global phone for validation as I needed to deploy. Global phone does not give the fine-grained phone type validation like phonelib, but I could not have people being unable to fill out our forms. Maybe I will switch back now. But closing the issue as I trust it works.
