### ISSUE TITLE
Mexico Parsing Nation Numbers

### ISSUE THREAD

**Issue by saelen** [daddyz/phonelib#132]
Seeing a difference when parsing Mexico numbers compared to the Google Phone number Implementation.  When putting in a national number for Mexico it seems to not parse it at all.

Example Number for MX country: 0445532231113
https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html parses without issue.

What is interesting though is Phonelib parses out 5215532231114 fine and translates it to the above national number.

**Comment by daddyz** [comment]
@saelen fixed in 0.6.20. Thanks for reporting
