### ISSUE TITLE
Extension Separate Symbols

### ISSUE THREAD

**Issue by CaioBianchi** [daddyz/phonelib#133]
According to the documentation, we're able to specify extension separate symbols (plural), however the initializer config only allows for a string:

`Phonelib.extension_separate_symbols = '#;'`

I want to be able to validate either `#`, `;`, `ext`, `extension`. Ideally this would simply be an array of strings assigned to that setting, but that doesn't seem to work. I also tried adding them separated by semi-colon, which allowed for every single match including those not listed.
What are my alternatives here?

E.g.: Ideally `+1 555-555-5555 ext. 5555` / `+1 555-555-5555;5555` / `+1 555-555-5555#5555` / `+1 555-555-5555 extension 5555` would all pass validation.

**Comment by daddyz** [comment]
@CaioBianchi  I added an option to assign array of strings to ```Phonelib.extension_separate_symbols``` like:
```ruby
Phonelib.extension_separate_symbols = %w(; # ext extension)
```
With such configuration your request will work.
