### ISSUE TITLE
Some Polish numbers incorrectly marked as invalid

### ISSUE THREAD

**Issue by pepawel** [daddyz/phonelib#135]
Hi,

Phonelib validation fails for some Polish numbers. It may be related to country code, which is "+48" for Poland. When number starts with "48" (which corresponds to "Radom" city in Poland) Phonelib probably thinks it is country code specification and ignores default_contry setting.

Please examine 2 examples below:

```
Phonelib.default_country = 'PL' # default country code is "+48"

phone = '716287061'
Phonelib.parse(phone).valid? # => true
Phonelib.parse('+48' + phone).valid? # => true

phone = '486287061'
Phonelib.parse(phone).valid? # => false <= here is the error
Phonelib.parse('+48' + phone).valid? # => true

```

**Comment by pepawel** [comment]
It is not a bug in Google library. Both numers pass as valid:
https://libphonenumber.appspot.com/phonenumberparser?number=716287061&country=PL
https://libphonenumber.appspot.com/phonenumberparser?number=486287061&country=PL

**Comment by daddyz** [comment]
@pepawel thanks for reporting. Check new version, now:
```ruby
Phonelib.parse('486287061').valid? # => true
```
