### ISSUE TITLE
country_specifier: doesn't seem to work / is confusing!

### ISSUE THREAD

**Issue by khalilgharbaoui** [daddyz/phonelib#136]
`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]`, `Rails 5.2.0` , `phonelib (0.6.21)`
Related issues: #109 

Suppose we have a Model: `MovingInquiry` that has an attribute `:client_number` which is a phone number with country code: `CH` or `ch` or `:ch`.
And in the initializer we have: `Phonelib.default_country = "CH"` set.
When we try to validate that: phone numbers are only from "CH" with the `country_specifier` validation method like this:

```ruby
validates :client_mobile, phone: { country_specifier: -> phone {
  phone.country.try(:upcase) 
}}
```
we get:
```
NoMethodError:
       undefined method `country' for #<MovingInquiry:0x00007facc3eebdb8>
```
This means that our model needs an attribute `country` with "CH" specified in it?
The documentation says: **_- allows to specify country for validation dynamically for each validation._**

I could do something like this but what is the point here? what is this supposed to validate now?
```ruby
validates :client_mobile, phone:{ country_specifier: -> phone {
  Phonelib.parse(phone.client_mobile).country.try(:upcase)
}}
```
I think country_specifier should not depend on an object having the `country` field/attribute/method defined and that country_specifier should grab and check the `country` from the passed phone number or an optional param or default_country dynamically?

Hope you have an explenation or solution for this?

Thanks.

**Comment by khalilgharbaoui** [comment]
I found a solution for my specific problem by adding a simplified custom validator:
`app/models/concerns/phone_country_code_validator.rb`
```ruby
class PhoneCountryCodeValidator < ActiveModel::Validator
  def validate(record)
    options[:fields].any? do |field|
      phone_number = record.send(field)
      phone_country = Phonelib.parse(phone_number).country
      phone_country_code = phone_country.to_s.upcase

      options[:country_codes].any? do |valid_country|
        valid_country_code = valid_country.to_s.upcase

        unless phone_country_code == valid_country_code
          record.errors.add(field, "has an invalid country code: #{phone_country_code} should be #{valid_country_code}")
        end
      end
    end
  end
end
```
And using it as follows:
`app/models/moving_inquiry.rb`
```ruby
validates_with PhoneCountryCodeValidator, fields: [:client_mobile, :client_home_number], country_codes: ["CH", :ch, Phonelib.default_country]
```
It uses 2 arrays `fields: []` and `country_codes: []`, its possible to add multiple country codes, and any and multiple fields.

Hope this helps improve this specific issue.

**Comment by daddyz** [comment]
@khalilgharbaoui I've added a ```countries``` option to validator, you can pass array of countries you want to validate with like:
```ruby
  validates :phone, phone: { countries: [:us, :ca] }
```
Hope it helps you to solve the issue

**Comment by khalilgharbaoui** [comment]
@daddyz I see. That is perfect. It works fine for me even like this:
`validates :client_mobile, phone: { countries: [Phonelib.default_country, :ch], types: [:mobile], message: "only swiss mobiles"}`

But when I add `possible: true` it becomes too permissive even accepting different country coded numbers. And not differentiating between country, mobile, fixed, national or e164 format.

But I guess that falls outside of the scope of this specific issue.

I'll just use it with strict mode because that does the trick and we won't be needing something like this anymore I guess:
`validates_format_of :client_mobile, with: /(\A07|\A.417|\A00417)/`

Thanks!

**Comment by daddyz** [comment]
@khalilgharbaoui once you parse the phone, returned instance have 2 methods ```countries``` and ```valid_countries```. Might happen that the number is possible for several countries while it will be valid only for specific one. Since this parameter allows array to be passed, gem does regular validation and is not doing strict check against some specified country.
