### ISSUE TITLE
Country name method?

### ISSUE THREAD

**Issue by monfresh** [daddyz/phonelib#139]
Hello. Thanks for this gem. It's great. I was trying to find a way to get the full country name from a parsed phone number, but I couldn't find one. Would you accept a pull request that added that feature?

**Comment by daddyz** [comment]
@monfresh Why not? Just make country list to be fetched from some geoname URI into the dat file and not as a hardcoded list in the gem itself. Countries list can be updated from time to time.

**Comment by daddyz** [comment]
@monfresh In v0.6.27 I added ```valid_country_name``` method to the instance of parsed number. It returns country name of phone in case it is valid, nil otherwise.

**Comment by monfresh** [comment]
Thanks!
