### ISSUE TITLE
getting phone invalid validation error

### ISSUE THREAD

**Issue by kajalwebonise** [daddyz/phonelib#141]
I am using the gem for validating Indian phone numbers and its showing many of numbers invalid while those are a valid number.
The series starts from 717177xxxx and 717825xxxx can you guys please revert me why this is happening.

**Comment by kajalwebonise** [comment]
I updated the gem my gem version is gem 'phonelib', '~> 0.6.24', but still getting same error

**Comment by daddyz** [comment]
@kajalwebonise can you provide example number?

**Comment by kajalwebonise** [comment]
7171774791, 7178256301

**Comment by daddyz** [comment]
Are you specifying country or default country is set?

**Comment by kajalwebonise** [comment]
using default country, and default country is IN

**Comment by daddyz** [comment]
Here is the result where both are valid
```ruby
2.4.1 :005 > Phonelib.default_country = 'IN'
 => "IN" 
2.4.1 :006 > Phonelib.parse('7171774791').valid?
 => true 
2.4.1 :007 > Phonelib.parse('7178256301').valid?
 => true 
2.4.1 :008 > Phonelib::VERSION
 => "0.6.24" 
```

**Comment by kajalwebonise** [comment]
Phonelib.parse('7171774791')
=> #<Phonelib::Phone:0x0000000b6c5a10
 @data=
  {"IN"=>
    {:id=>"IN",
     :country_code=>"91",
     :international_prefix=>"00",
     :national_prefix=>"0",
     :leading_zero_possible=>"true",
     :national_prefix_formatting_rule=>"$NP$FG",
     :national_prefix_optional_when_formatting=>"true",
     :mobile_number_portable_region=>"true",
     :double_prefix=>true,
     :national=>"7171774791",
     :format=>
      {:pattern=>"(\\d{4})(\\d{3})(\\d{3})",
       :leading_digits=>"1(?:[23579]|[468][1-9])|[2-8]",
       :format=>"$1 $2 $3"},
     :valid=>[:fixed_line],
     :possible=>[:toll_free, :uan, :fixed_or_mobile]}},
 @extension="",
 @national_number="7171774791",
 @original="7171774791",
 @sanitized="7171774791">


here valid  = [:fixed_line]

Phonelib.parse('7879238675')
=> #<Phonelib::Phone:0x0000000a4822b8
 @data=
  {"IN"=>
    {:id=>"IN",
     :country_code=>"91",
     :international_prefix=>"00",
     :national_prefix=>"0",
     :leading_zero_possible=>"true",
     :national_prefix_formatting_rule=>"$NP$FG",
     :national_prefix_optional_when_formatting=>"true",
     :mobile_number_portable_region=>"true",
     :double_prefix=>true,
     :national=>"7879238675",
     :format=>
      {:pattern=>"(\\d{5})(\\d{5})",
       :leading_digits=>
        "600|7(?:0|19[0-5]|2(?:[0235679]|[14][017-9]|8(?:[0-569]|[78][089])|9[389])|3(?:[05-8]|1(?:[089]|7[5-9])|2(?:[5-8]|[0-49][089])|3[017-9]|4(?:[07-9]|11)|9(?:[01689]|[2345][089]|40|7[0189]))|4(?:[056]|1(?:[0135-9]|[23][089]|2[089]|4[089])|2(?:0[089]|[1-7][089]|[89])|3(?:[0-8][089]|9)|4(?:[089]|11|7[02-8])|7(?:[089]|11|7[02-8])|8(?:[0-24-7][089]|[389])|9(?:[0-7][089]|[89]))|5(?:[0346-9]|1(?:[0189]|7[02-9])|2(?:[03-9]|[12][089])|5[017-9])|6(?:[06-9]|1[0-257-9]|2[0-5]|3[19]|4(?:6[89]|[7-9][089])|5(?:[0-367][089]|[4589]))|7(?:0(?:[02-9]|1[089])|[1-9])|8(?:[0-79]|8(?:0[0189]|11|8[013-9]|9))|9(?:[08]|7(?:[2-8]|9[07-9])|9(?:[03-9]|11|2[234])))|8(?:0(?:[01589]|6[67]|7(?:[2-8]|9[056]))|1(?:[02-57-9]|1(?:[0135-9]|22|44)|6[089])|2(?:0[08]|[14](?:[089]|7[02-8])|[235-9])|3(?:[0357-9]|1(?:[089]|7[02-6])|2(?:[09]|77|8[0-689])|4[1-9]|6(?:[089]|7[02-7]))|[45]|6(?:[02457-9]|1(?:[089]|7[02-8])|3(?:[089]|7[02358])|6(?:[08]|7[02-8]|9[01]))|7(?:0[07-9]|[1-69]|7(?:[089]|7[02-8])|8(?:[089]|7[02-8]))|8(?:[0-25-9]|3(?:[089]|7[02-8])|4(?:[0489]|7[02-68]))|9(?:[02-9]|1(?:[0289]|7[2-6])))|9",
       :format=>"$1 $2"},
     :valid=>[:fixed_or_mobile],
     :possible=>[:toll_free, :uan, :fixed_or_mobile]}},
 @extension="",
 @national_number="7879238675",
 @original="7879238675",
 @sanitized="7879238675">

here valid = [:fixed_or_mobile]
first no is not accepting but last one is working

**Comment by daddyz** [comment]
How are you doing your validation?

**Comment by kajalwebonise** [comment]
validates :mobile_number,
            phone: { possible: false, allow_blank: true, types: [:mobile] },
            presence: true
