### ISSUE TITLE
(Request) Update phone data

### ISSUE THREAD

**Issue by Looooong** [daddyz/phonelib#142]
Please. I need latest data on carrier info for validation purpose. Btw, is there a way to automatically synchronize data between this gem and Google libphonenumber?

**Comment by daddyz** [comment]
@Looooong I updated the data, will think of a way to auto update

**Comment by Looooong** [comment]
I suggest that we put the phone data into a cache and add methods to allow users to choose cache store (memory store, Redis store, file store...) as well as when to update this cache with live data from Google.

I will be glad if I can help you to implement this functionality.

**Comment by daddyz** [comment]
@Looooong Sure you can do the pull request. Just keep in mind that data is loaded to variable on first request and if the app keeps running it's not being read again from file until app restart. So it's like in memory cache.
