### ISSUE TITLE
Get '00' instead of '+' in international phone number

### ISSUE THREAD

**Issue by nicolasrouanne** [daddyz/phonelib#153]
Is there a way to get `00` instead of `+` in an international phone number?

Something like that:
```ruby
Phonelib.parse('+33601020304').international(prefix: "00")
=> "0033601020304"
```

It could be also another method, such as `.international_00`

> I can open a PR if issue is accepted 😃

**Comment by daddyz** [comment]
@nicolasrouanne Hi, I implemented required behavior a bit different. Anyway thanks for PR.
```ruby
p = Phonelib.parse '1 212 555 1234'
p.international('00') # => "001 212-555-1234"
p.international_00 # => "001 212-555-1234"
p.international_xx # => "xx1 212-555-1234"
p.e164('+') # => "+12125551234"
p.e164_00 # => "0012125551234"
```
