### ISSUE TITLE
Wrong US and Canada national format

### ISSUE THREAD

**Issue by philippevezina** [daddyz/phonelib#155]
The `national` format return for an American or Canadian number is `555 555 5555` but it should actually be `(555) 555-5555`.

**Comment by daddyz** [comment]
@philippevezina if you are parsing valid phone number, then it will be ok
```ruby
p = Phonelib.parse '1 212 555 1234'
p.national # => "(212) 555-1234"
```

**Comment by philippevezina** [comment]
@daddyz You're right! I did more testing and turns out the problem is only for Canadian numbers: `Phonelib.parse('1 418 928 3648').national => "418 928 3648"`
