### ISSUE TITLE
Phone numbers without international prefix and default country code being considered valid

### ISSUE THREAD

**Issue by PedroMGSilva** [daddyz/phonelib#159]
Hi @daddyz!

I am facing the following issue:

When I run `Phonelib.parse('9888888888')` (9888888888 being an Indian phone number without country code) I get an invalid number.

However, when I run `Phonelib.parse('9111111111')` (9111111111 being also an Indian phone number without country code) I get a valid number. When I try to access the e164 format of the given number, `Phonelib.parse('9111111111').e164` I get `+919111111111`.

Shouldn't 9111111111 be an invalid number when no default country code is given? Why is it considering valid and adding a country code?

**Comment by PedroMGSilva** [comment]
I have opened this PR that I think it fixes the problem:

https://github.com/daddyz/phonelib/pull/161

**Comment by daddyz** [comment]
@PedroMGSilva PR accepted in v0.6.33
