### ISSUE TITLE
full_international returns NA

### ISSUE THREAD

**Issue by futuretap** [daddyz/phonelib#160]
For the Australian number `+61 13 12 21` phonelib returns `+61 NA` for `full_international`:

```
n = Phonelib.parse('+61 13 12 21', 'au')
n.full_international # "+61 NA"
n.e164 # "+61131221"  

```

However, `e164` works fine. However, https://libphonenumber.appspot.com returns a correct International format so I suspect there's something wrong in phonelib.

**Comment by daddyz** [comment]
@futuretap thanks for reporting, fixed in v0.6.32
