### ISSUE TITLE
Validates allow_blank: true doesn't seem to be working

### ISSUE THREAD

**Issue by voska** [daddyz/phonelib#162]
When I try to add an object with a blank number, it fails validation.

Here's my model:
```
class Object < ApplicationRecord
  validates :phone, phone: {allow_blank: true, extensions: false }

  def phone
    Phonelib.parse(super)
  end
end
```

My initializer:
```
Phonelib.default_country = "US"
Phonelib.strict_check = true
```

What happens:
```
o.phone = nil
o.save
=> false
```

`Using phonelib 0.6.33`

**Comment by voska** [comment]
I've found that when I remove the below code in the model, it works again. I can't figure out why this is causing the validation to fail though.

```
  def phone
    Phonelib.parse(super)
  end
```

**Comment by arielkirkwood** [comment]
When you save your model, what is displayed in `o.errors.messages`?

**Comment by voska** [comment]
It was saying that Phone is not valid.

I think it was a name conflict because I had a method tied to that attribute, so when PhoneLib validated it, it was validating the phone method, not the phone attribute.

I solved the problem by renaming the attribute to phone_number 

Working code below:

```
class Object < ApplicationRecord
  validates :phone_number, phone: {allow_blank: true, extensions: false }

  def phone
    Phonelib.parse(phone_number)
  end
end
```

**Comment by daddyz** [comment]
@voska This is how rails work. Validator method is defined like this: ```def validate_each(record, attribute, value)```, I am checking ```value``` variable, which is passed by rails, and rails calls ```attribute``` method on model in order to get its value. It's not good to override it, can cause unexpected problems in other places.
