### ISSUE TITLE
Vietnam valid phone numbers with prefix same as a country code, seem to fail vaildation. 

### ISSUE THREAD

**Issue by bndeepti** [daddyz/phonelib#171]
We have encountered a issue as follows, 

number1 = "902962207"
Phonelib.parse(number1) returns "+84902962207"

number2 = "844666531"
Phonelib.parse(number2) returns the same "+844666531"

number2 is a valid Vietnam phone number.
Vietnam updated phone prefixes last year. By this, 84 is a valid prefix (without country code).

This does not seem to work with latest version of phonelib. Any resolutions ?

**Comment by daddyz** [comment]
@bndeepti fixed in v0.6.37
