### ISSUE TITLE
Netherlands phone number returns as invalid

### ISSUE THREAD

**Issue by bdmac** [daddyz/phonelib#173]
We just purchased a phone number from Twilio in the Netherlands but cannot add it to our system because it is failing phone number validation. The number from Twilio is:

+31 97014202081

```
[2] pry(main)> Phonelib.valid? "+3197014202081"
=> false
```

**Comment by daddyz** [comment]
@bdmac I checked against original google libphonenumber, number validation fails as well. You need to [open an issue](https://issuetracker.google.com/issues/new?component=192347&template=829703) in original google lib.

**Comment by hnatt** [comment]
Ironically, while Twilio provides these numbers to purchase, their Lookup API does not support them. I'm having the same exact issue as @bdmac and tried to work around it by falling back to Twilio Lookup API, but it returns 404 for these numbers.

A person from Google wrote in @bdmac's ticket for libphonenumber:
> We should be adding support to it by at least Q1 2020

So maybe we can have it soon.
