### ISSUE TITLE
local_number returns area code

### ISSUE THREAD

**Issue by jasonperrone** [daddyz/phonelib#181]
I'm very confused. I thought that local_number was supposed to return the phone number without area code:

``
p = Phonelib.parse('+15173375337');
p.local_number => '(517) 337-5337'
``

Huh?

**Comment by daddyz** [comment]
@jasonperrone Local number actually returns number without country code but with local prefix, not the number within the state.

**Comment by jasonperrone** [comment]
Thanks @daddyz .  Perhaps a suggested new format? ;-)
