### ISSUE TITLE
Canadian area code returns as invalid

### ISSUE THREAD

**Issue by tomm-ylee** [daddyz/phonelib#184]
Numbers from the "672" area code are all failing validation tests. For example with "6729999999" I am getting:

`2.6.5 :007 > Phonelib.valid? '6729999999'
false`

Currently using version `0.6.41` on Rails 5.2.4.1 . Testing against the libphonenumber demo, that number should be valid.

**Comment by seawang** [comment]
Confirmed [libphonenumber demo ](https://libphonenumber.appspot.com/phonenumberparser?number=%2B16729999999&country=CA)accepts this number



Validation Results
--

- true
- true
- true
- CA
- FIXED_LINE_OR_MOBILE

**Comment by LanceOlsen** [comment]
This area code was added in May, 2019. Would love to get an update, thanks!

**Comment by daddyz** [comment]
@LanceOlsen @seawang I released 0.6.42, it's "valid" there
