### ISSUE TITLE
Some Nigerian's phone number return invalid (whereas google libphonenumber does not)

### ISSUE THREAD

**Issue by guillaumedenece** [daddyz/phonelib#190]
Hi,

`Phonelib.valid?('2349049974092')` returns false

Whereas google phonelib indicates that this phone number is valid.
Find the test on google phonelib [here](http://libphonenumber.appspot.com/phonenumberparser?number=2349049974092&country=NG)

I can confirm that this phone number is valid since I tried to send it an SMS and it has been delivered.

Thank's a lot in advance

**Comment by CamiloGarciaLaRotta** [comment]
bumping as it's the same with Singapore numbers:
```ruby
irb(main):017:0> Phonelib.valid_for_country? "+6589397702", "SG"
=> false
```
Google Phonelib says [it's valid](http://libphonenumber.appspot.com/phonenumberparser?number=%2B6589393220&country=SG)

**Comment by CamiloGarciaLaRotta** [comment]
digging a bit into the source code, I see that both Singapore and Nigeria are part of the gem's data:

```ruby
irb(main):018:0> phone_data[:country_names]["SG"]
=> "Singapore"
irb(main):019:0> phone_data[:country_names]["NG"]
=> "Nigeria"
```

**Comment by daddyz** [comment]
@CamiloGarciaLaRotta in version 0.6.46 returns `true` for both numbers
