### ISSUE TITLE
international(false) returns symbols with invalid numbers

### ISSUE THREAD

**Issue by blythedunham** [daddyz/phonelib#196]
With US set as the default, calling `international(false)`  has an unexpected  "+"

```
> Phonelib.parse(12869453481).international(false)
 => "+12869453481"
```

I would expect this to return "12869453481". I noticed that this number returns `false` for `valid?`

With a real US area code (206 instead of 286) it works as expected. 
```
> Phonelib.parse(12069453481).international(false)
 => "12069453481"
```

**Comment by daddyz** [comment]
@blythedunham the bug is actually the missing "+" sign when `false` specified. Now both cases return with "+"
```ruby
Phonelib.parse(12869453481).international(false) # => "+12869453481"
Phonelib.parse(12069453481).international(false) # => "+12069453481"
```
Thanks for reporting
