### ISSUE TITLE
Phone Numbers with random characters/letters shows as valid

### ISSUE THREAD

**Issue by sushilsainju** [daddyz/phonelib#201]
I am trying to use this gem for phone validation but as I was testing some random numbers, i got weird results such as 
`Phonelib.valid?('122322222dasmmdas31')
Phonelib.valid?('122322222dasmmdas31s')
Phonelib.valid?('122322222dasmmdas31ds')` all returning true. 
I don't believe this is a desired behaviour.

**Comment by daddyz** [comment]
For parsing number is getting sanitized, in case this is not a desired behavior you may set `Phonelib.strict_check = true` in initializer
