### ISSUE TITLE
possible? predicate returns true for things which aren't phone numbers

### ISSUE THREAD

**Issue by james-caresnap** [daddyz/phonelib#203]
phonelib (0.6.46)
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]

`libphonenumber` [returns false](https://libphonenumber.appspot.com/phonenumberparser?number=2062407123%40gmail.com&country=US) for all these cases:
```
irb(main):004:0> Phonelib.valid? "7135551212@gmail.com"
=> true
irb(main):005:0> Phonelib.possible? "7135551212@gmail.com"
=> true
irb(main):006:0> Phonelib.valid_for_country? "7135551212@gmail.com", "US"
=> true
```

Additionally there's some related degenerate parsing cases:
```
irb(main):022:0> Phonelib.parse("foo3@bar.com").full_e164
=> "+3"
```

**Comment by james-caresnap** [comment]
I also have these settings:
```
Phonelib.default_country = "US"
Phonelib.extension_separate_symbols = ["x", ";"]
```

**Comment by james-caresnap** [comment]
The `@gmail.com` gets gsubbed to oblivion by `sanitize` here:
https://github.com/daddyz/phonelib/blob/master/lib/phonelib/phone.rb#L54

Turning on strict_check solves that problem but then the parser no longer tolerates phone numbers like:
 - `(713) 555-1212`
 - `713.555.1212`
 - etc..

**Comment by daddyz** [comment]
@james-caresnap in v0.6.47 I added `Phonelib.sanitize_regex` which helps to control which symbols to sanitize.
Strict mode cuts "+" only, by default gem cuts all that is not number, with this variable you may achieve what you need.
```ruby
Phonelib.sanitize_regex = '[\.\-\(\) \;\+]'
```
This will cut all the symbols you mentioned.
