### ISSUE TITLE
How can I change formating for specisfic country?

### ISSUE THREAD

**Issue by StanZhuravlev** [daddyz/phonelib#204]
I use a russian phones, and see: 

```ruby
phone = Phonelib.parse("+74951234567", "RU")
expect(phone.full_international).to eq("+7 495 123-45-67")
```

But I want set a pattern for a more right format:

```ruby
phone = Phonelib.parse("+74951234567", "RU")
expect(phone.full_international).to eq("+7 (495) 123-45-67")
```

How I can made this?

**Comment by daddyz** [comment]
@StanZhuravlev currently the only option is to use `Phonelib.override_phone_data` config variable.
Refer to readme about this variable, you will need to dump `Phonelib.phone_data['RU']`.
