### ISSUE TITLE
Update data to libphonenumber v8.12.16

### ISSUE THREAD

**Issue by adrianchinghc** [daddyz/phonelib#211]
Recently got an update that the latest release of libphonenumber includes some updates with new mobile number ranges for our country. 

Is there any ways we can help with the data update? Appreciate it 🙏🏻

**Comment by daddyz** [comment]
@adrianchinghc data has be updated

**Comment by adrianchinghc** [comment]
> @adrianchinghc data has be updated

Awesome! Thanks @daddyz
