### ISSUE TITLE
Weird data in phone_ext_data

### ISSUE THREAD

**Issue by husam212** [daddyz/phonelib#214]
The first element in `phone_ext_data` contains the following array:
```
["iso alpha2", "name"]
```

This is not exposed API so it might not be a bug, it started in recent versions (> 0.6.45).

**Comment by daddyz** [comment]
@husam212 strange, can you provide your environment since I don't see this locally?

**Comment by husam212** [comment]
@daddyz I can reproduce the issue with version 0.6.47.

[test.zip](https://github.com/daddyz/phonelib/files/6178281/test.zip)

**Comment by daddyz** [comment]
So you got to :country_names key:
```ruby
Phonelib.phone_ext_data[:country_names].first
=> ["iso alpha2", "name"]
```
Will be fixed in next version.
