### ISSUE TITLE
Ivory Coast, 8 -> 10 digits, and latest libphonenumber version

### ISSUE THREAD

**Issue by plcstevens** [daddyz/phonelib#215]
Hi,

We have seen an issue arise with our Ivory Coast customers due to a recent change in the digits for phone numbers in that country. (article in french: https://www.rfi.fr/fr/afrique/20201226-c%C3%B4te-d-ivoire-les-num%C3%A9ros-de-t%C3%A9l%C3%A9phone-passeront-de-8-%C3%A0-10-chiffres-le-31-janvier)

It seems like the libphonenumber most recent version handles this: https://github.com/google/libphonenumber/blob/master/release_notes.txt#L4 but I have not been able to fork/import the data because the geonames API task is failing.

Are you able to update the data and release a new version to support these most recent changes?

Thank you

**Comment by daddyz** [comment]
@plcstevens updated data and released
