### ISSUE TITLE
Instance variable @ext_data not initialized warning on use

### ISSUE THREAD

**Issue by wflanagan** [daddyz/phonelib#217]
versions/2.7.2/lib/ruby/gems/2.7.0/gems/phonelib-0.6.48/lib/phonelib/phone_extended_data.rb:61: warning: instance variable @ext_data not initialized

We see this a lot running tests on Ruby 2.7.2. FYI.

**Comment by daddyz** [comment]
@wflanagan handled this, thanks for reporting
