### ISSUE TITLE
How to run , and csv , thnx

### ISSUE THREAD

**Issue by hummans** [daddyz/phonelib#221]
Hello i m new at this and ruby .
How do i install this specificaly?
After that what command should i do to run it?
Is this a cli or what?
And is possible to make csv upload and then get generated csv ? Thnx

**Comment by daddyz** [comment]
@hummans everything is written in [readme](https://github.com/daddyz/phonelib/blob/master/README.md).
This is a ruby gem (library), this can be installed with bundler or simply with "gem install" command. This gem can be used with any ruby project.

**Comment by hummans** [comment]
Thnx for your reply
that was what i needed to know . that that can be run in any project
wuold be great if you ad a demo example here
i m trying to make as input a txt or csv file then it generates a new one with verifications
any help for this?
thnx
