### ISSUE TITLE
Can't parse  10 digits HK number eg`+8521234567890`.

### ISSUE THREAD

**Issue by atsuya-kose** [daddyz/phonelib#222]
Python's `phonenumbers` can parse that.

```
In [2]: phonenumbers.parse("+8521234567890")
Out[2]: PhoneNumber(country_code=852, national_number=1234567890, extension=None, italian_leading_zero=None, number_of_leading_zeros=None, country_code_source=0, preferred_domestic_carrier_code=None)
```

But phonlib can't parse  10 digits HK number like`+8521234567890`.
```
[1] pry(main)> Phonelib.parse("+8521234567890")
=> #<Phonelib::Phone:0x0000564819b6d778
 @data={},
 @extension="",
 @national_number="8521234567890",
 @original="+8521234567890",
 @original_s="+8521234567890",
 @sanitized="8521234567890">
```

I checked 6,7,8,9,11 digits was working.

**Comment by daddyz** [comment]
@atsuya-kose   This number is also parsed as invalid in original libphonenumber. You can check it [here](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) and [open an issue for them](https://issuetracker.google.com/issues/new?component=192347&template=829703). Gem's data is based on it.
I have released an "additional_regexes" feature that can help to overcome this issue, refer to [README.md](https://github.com/daddyz/phonelib/blob/master/README.md) about usage or you can also use ```Phonelib.override_phone_data```

**Comment by atsuya-kose** [comment]
Oh I see. Thank you very much!!
