### ISSUE TITLE
Invalid Singaporean numbers beginning with 8

### ISSUE THREAD

**Issue by seanneale** [daddyz/phonelib#248]
Valid Singaporean numbers are being return as invalid. 80221069 is being returned as invalid for SG but it is valid on the [google phonelib](https://libphonenumber.appspot.com/phonenumberparser?number=80221068&country=SG)

```ruby
Phonelib.valid_for_country?("80221069", "SG") # false
```

I have confirmed the number is valid but it seems to be affecting all phone numbers beginning with 8. Any idea why this are invalid?

Thanks for looking into this, I hope I haven't missed a previous discussion about it

**Comment by daddyz** [comment]
@seanneale thanks for reporting.
After data update in v0.6.56 I see it returns true, please update
