### ISSUE TITLE
Support for ivory coast (+225) new format

### ISSUE THREAD

**Issue by saurgoel** [daddyz/phonelib#250]
The latest version doesn't support formatting for the new Ivory Coast phone number, they will switch from 8 digits to 10 digits.

More info here - 
https://groups.google.com/g/libphonenumber-discuss/c/9bM1W6aRe10

**Comment by daddyz** [comment]
@saurgoel thanks for reporting. 
After data update in v0.6.56 I see that international method returns same result as in example of this thread.
