### ISSUE TITLE
digit being removed from Mexico numbers

### ISSUE THREAD

**Issue by farjadfazli** [daddyz/phonelib#254]
We have a text-message based learning platform and noticed that a `1` is being removed from Mexico numbers when they are parsed with e164 formatting (e.g. `+5215562000000` becomes `+525562000000`). Sending a message to the number without the `1` is working but when a reply comes in the `From` number includes the `1`. We want to understand why the `1` is being removed here?

**Comment by daddyz** [comment]
Hi @farjadfazli , here is a link to [Mexico Simplifies its Telephone Dialing Rules](https://www.mexperience.com/mexico-simplifies-telephone-dialing-rules/), which describes the change. Phonelib bases its parsing on Google's libphonenumber, you can check and see same result [here](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html).
So no issue here.
