### ISSUE TITLE
Australian landline numbers beginning with 08.

### ISSUE THREAD

**Issue by thomashexton** [daddyz/phonelib#257]
Thank you for a great gem. It's got my back a lot, but I've been unsuccessful in finding a solution to my following issue. And to be honest, I'm not able to work out if it's a bug in `phonelib` or something related to Google's libphonenumber? (And if it is the latter, I've also been unsuccessful in finding some docs to explain how to overwrite the libphonenumner locally, as this Gem's README specifies I can do (via `Phonelib.override_phone_data` method).

From my testing, all of the Australian landline state prefix codes `02, 03, 04, 07` ([as defined by Government](https://www.australia.gov.au/telephone-country-and-area-codes)) work except for the `08` prefix.

Working AUS code example: ✅
```
Phonelib.parse("(07) 4444 0008").national
> "(07) 4444 0008"
Phonelib.parse("(07) 4444 0008").e164
>  "+61744440008"
```

Broken AUS code example: ❌ 
```
Phonelib.parse("(08) 4444 0008").national
> "844440008"
Phonelib.parse("(08) 4444 0008").e164
> "+610844440008" # please note: additional 0 just after the +61
```

Any help would be appreciated.

**Comment by daddyz** [comment]
@thomashexton I updated data of the gem, but it's still being parsed incorrectly. Check section [describing parsing issue](https://github.com/daddyz/phonelib#incorrect-parsing-or-validation). You can open issue for libphonenumber or just add additional regexes for AUS in initializer.
