### ISSUE TITLE
Problems with Ivory Coast numbers

### ISSUE THREAD

**Issue by joaolrpaulo** [daddyz/phonelib#263]
Seems that a couple of problems with Ivory Coast numbers have been fixed in https://github.com/google/libphonenumber/releases/tag/v8.12.55.

I was able to validate this by using the suggested method here https://github.com/daddyz/phonelib/issues/230#issuecomment-904789315.

Example number: `+2252722220182`.

Can I request an update to the metadata?

Thanks in advance!

**Comment by daddyz** [comment]
@joaolrpaulo check version 0.7.3, updated right now

**Comment by joaolrpaulo** [comment]
It solved our problems. Thanks for the quick update 🙏🏼
