### ISSUE TITLE
String inside number shows valid

### ISSUE THREAD

**Issue by rajanverma-me** [daddyz/phonelib#265]
The command below evaluates to `true`;

`Phonelib.valid_for_country? "91977947ada1801", :in`

I don't think any country has this pattern of phone numbers. 
This should be a general case failure.

**Comment by daddyz** [comment]
@rajanverma-me Phonelib does sanitization prior to parsing, but you can enable strict check in initializer
```ruby
Phonelib.valid_for_country?("91977947ada1801", :in) # => true 

Phonelib.strict_check = true
Phonelib.valid_for_country?("91977947ada1801", :in) # => false
Phonelib.valid_for_country?("919779471801", :in) # => true 
```
