### ISSUE TITLE
Valid Australian phone numbers starting with `483` failed validation

### ISSUE THREAD

**Issue by nilstzh** [daddyz/phonelib#270]
We have an Australian phone number that is falsely invalidated by `phonelib`.

Here is an example:
```
irb(main):022:0> Phonelib.parse('61483910455').valid?
=> false
```

I the libphonenumber demo it is parsed correctly.

<img width="670" alt="Screenshot 2023-02-27 at 09 55 05" src="https://user-images.githubusercontent.com/22571691/221517926-79cddd53-2393-44f2-a3a0-4dec699a6d62.png">

Is there a way to fix it?

EDIT: looks like this is a problem for all numbers starting with `483`. Numbers starting with `482` or `484` for example doesn't have this problem

**Comment by ElMassimo** [comment]
This seems fixed in the latest version of the library.
