### ISSUE TITLE
Parsing mistake with (+1) 907 prefix

### ISSUE THREAD

**Issue by jeppeliisberg** [daddyz/phonelib#273]
Example: (907) 581-1400 parses to timezone "Honolulu" but should have been Unalaska, AK, USA

https://24timezones.com/907/area-code

**Comment by daddyz** [comment]
@jeppeliisberg I am taking the data from original library, based on [this line](https://github.com/google/libphonenumber/blob/master/resources/timezones/map_data.txt#L1937) timezone for 1907581 should be Pacific/Honolulu. If that's not correct you need to open an issue to libphonenumber lib
