### ISSUE TITLE
Phone number is valid however it contains alphabetic characters

### ISSUE THREAD

**Issue by Mohab-Kahla-TrianglZ** [daddyz/phonelib#299]
I guess inserting an alphabetic character should invalidate the phone number, right?

<img width="358" alt="image" src="https://github.com/daddyz/phonelib/assets/99013680/259f805b-8c35-473a-837b-eba96623ba01">

**Comment by daddyz** [comment]
@Mohab-Kahla-TrianglZ there is a configuration option for such cases:
```ruby
Phonelib.strict_check = true
```
