### ISSUE TITLE
Changed bahavior upgrading from 0.8.0 to 0.8.1

### ISSUE THREAD

**Issue by tilo** [daddyz/phonelib#303]
looks like the API for PhoneLib changed from version 0.8.0 to 0.8.1

before you could do this:

`phone = Phonelib.parse(phone_number, ["US", "CA"])`

now you have to do this:

```
phone = nil
phone ||= Phonelib.parse(phone_number, "US")
phone ||= Phonelib.parse(phone_number, "CA")
```

* such a change in behavior should be caught by failing tests in PhoneLib
   -> there was no test coverage
* any change in behavior should rev-up more than just the last digit of the version
   -> see https://semver.org/

**Comment by tilo** [comment]
@daddyz did you see this?

**Comment by daddyz** [comment]
@tilo interesting undocumented behavior. I never saw that method being used like that, it's not documented and not tested. I tried it locally on 0.8.9 and it works. Can you specify your ruby version?

**Comment by tilo** [comment]
> @tilo interesting undocumented behavior. I never saw that method being used like that, it's not documented and not tested. I tried it locally on 0.8.9 and it works. Can you specify your ruby version?

we're using Ruby 3.2.2

**Comment by daddyz** [comment]
@tilo can you test latest version?

**Comment by daddyz** [comment]
regardless, there is a configuration option that allows several countries:
```ruby
Phonelib.default_country = ['US', 'CA']
phone = Phonelib.parse(phone_number)
```

**Comment by daddyz** [comment]
@tilo check version 0.9.1, I saw this happening for possible numbers only, with valid numbers it was working properly

**Comment by tilo** [comment]
looks like our tests are passing with 0.9.1

**Comment by daddyz** [comment]
great, closing the issue
