### ISSUE TITLE
Valid Argentina number reported as invalid

### ISSUE THREAD

**Issue by matiasm15** [daddyz/phonelib#304]
The number "+540111557447700" is valid according the [parser demo](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html):
![Screenshot_20240421_232913](https://github.com/daddyz/phonelib/assets/6295725/b0c57c3a-eade-4b56-b6db-8e34eef726bd)

But the gem reported as invalid:
```
Phonelib.parse('+540111557447700', 'AR').valid_for_country?('AR')
=> false
```

**Comment by daddyz** [comment]
@matiasm15 fixed in v0.9.0, thanks for reporting
