### ISSUE TITLE
valid? returns false for valid number in CA

### ISSUE THREAD

**Issue by akcrono** [daddyz/phonelib#310]
Per [google's libphonenumber](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html), this number is valid in CA, but returns false for Canada:
```
[9] pry(main)> Phonelib.default_country = 'CA'
=> "CA"
[10] pry(main)> Phonelib.valid? '18794908676'
=> false
```

Looking at libphonenumber, when they parse a CA number, they use ["(?:[2-8]\\d|90)\\d{8}|3\\d{6}"](https://github.com/google/libphonenumber/blame/3f71d47bf61e97ab1de66efb5816ceb994e202af/javascript/i18n/phonenumbers/metadata.js#L1455). Phonelib uses "(\\d{3})(\\d{3})(\\d{4})".  When I add that additional regex, I get the expected result:
```
[14] pry(main)> Phonelib.add_additional_regex :ca, Phonelib::Core::MOBILE, "(?:[2-8]\\d|90)\\d{8}|3\\d{6}"
=> ["(?:[2-8]\\d|90)\\d{8}|3\\d{6}"]
[15] pry(main)> Phonelib.valid? '18794908676'
=> true
```

Another interesting observation:

Phone number '18794908676' is valid in China.  However:
```
[14] pry(main)> Phonelib.valid? '18794908676'
=> false
```
When I set the default country to CN:
```
[15] pry(main)> Phonelib.default_country = "CN"
=> "CN"
[16] pry(main)> Phonelib.valid? '18794908676'
=> true
```

If I haven't set a default country, this should return true if it's valid for any country.  The current context I'm using this in does not have a realistic concept of a default country (a member of any country can input a number).

**Comment by daddyz** [comment]
updated in v0.9.2
