### ISSUE TITLE
Support for 2775* numbers

### ISSUE THREAD

**Issue by sinpai** [daddyz/phonelib#313]
Hi `phonelib` team!
I want express my deep appreciation for your work! 

Unfortunately, we are encountered one specific case when 2775******* number is shown as invalid in `phonelib`, however when we check the number at https://libphonenumber.appspot.com/ it shows as valid.

As it shown on release notes of `libphonenumber` they updated a lot of data since last release of `phonelib` gem.
URL with release notes - https://github.com/google/libphonenumber/blob/master/release_notes.txt

Link to a change added that gives this difference in validness of the number between `phonelib` and `libphonenumber` - https://github.com/google/libphonenumber/commit/c38b9890d9833186c3bb0686d76208a78a74b261#diff-c72e85b510150cefcfcc0d0a58600a4d73ccd71341ac46a8922aedcbd9f652df (Added carrier with 2775 prefix).

Could we ask you to update data to the latest one available from `libphonenumber` if you got a chance?

**Comment by tvandergeer** [comment]
It would be great to have a documented procedure for generating the `phone_data.dat` and `extended_data.dat` ourselves. We can then send PRs to update the data.

**Comment by daddyz** [comment]
in general there is a rake task to update the data and setter for override file, usually I am updating data and releasing version once a month, just had a busy August.

**Comment by tvandergeer** [comment]
Thanks for this! We'll try to find how the rake task and setter work so we don't need to rely on the monthly releases. If you have any documentation for that, please share!

Keep up the great work!
