### ISSUE TITLE
Universal International Freephone Number not considered valid

### ISSUE THREAD

**Issue by pedro-trindade** [daddyz/phonelib#314]
Hello amazing `PhoneLib` team 👋🏻 
Per [google's libphonenumber](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html), universal international freephone numbers, such as `+80050001001`, are considered valid:

> ****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): true
Phone Number region: 001
Result from getNumberType(): TOLL_FREE

However, using PhoneLib I'm getting these results:

> inspect: #<Phonelib::Phone:0x000000010529b318 @original="+80050001001", @extension="", @sanitized="80050001001", @original_s="+80050001001", @data={}, @national_number="80050001001">
valid?: false
invalid?: true
possible?: false
impossible?: true
types: []
type: 
human_types: []
human_type: 
possible_types: []
countries: []
country: 
valid_countries: []
valid_country: 
country_code: 
national: 80050001001
international: +80050001001
e164: +80050001001
national_number: 80050001001

Would it be possible to add support for these numbers in PhoneLib?
[Wikipedia](https://en.wikipedia.org/wiki/Toll-free_telephone_number#International) info for UIFN

Thank you so much for your incredible work and your support! 🙏🏻

**Comment by daddyz** [comment]
@pedro-trindade added support for such numbers
```ruby
p =Phonelib.parse('+80050001001') # => #<Phonelib::Phone:0x000060350c879500 @original="+80050001001", ... 
p.valid? # => true 
p.country # => "International 800" 
```
