### ISSUE TITLE
Phonelib.parse Fails to Identify Country for Brazilian Numbers Without "+" Prefix

### ISSUE THREAD

**Issue by geraldaddey** [daddyz/phonelib#326]
## Description
 
When parsing a Brazilian phone number without the + prefix, the Phonelib.parse method does not correctly identify the country. However, adding the + prefix works as expected.

```
require 'phonelib'

Phonelib.parse('554197520226').country

=> nil

Phonelib.parse('+554197520226').country

=> "BR"

``` 

## Expected Behavior
The method should correctly identify the country as Brazil ("BR") regardless of whether the number is prefixed with +.

## Actual Behavior
The method returns nil when the + prefix is omitted.

**Comment by daddyz** [comment]
@geraldaddey fixed in 0.10.3
