### ISSUE TITLE
Parsing German Five-digit area codes

### ISSUE THREAD

**Issue by rschaden** [daddyz/phonelib#43]
```
phone_number = Phonelib.parse('+4902304973401', 'DE')
phone_number.national # => "023 04973401" 
```
But the correct national formatting according to http://libphonenumber.appspot.com/phonenumberparser would be "02304 973401", 02304 being the prefix for Schwerte in North Rhine-Westphalia. 

I found that in [get_number_format](https://github.com/daddyz/phonelib/blob/master/lib/phonelib/phone_analyzer.rb#L192-L198) way too many formats match because the ^-operator only applies to the first term of the Regexp (so leading_digits "3[02]|40|[68]9" is incorrectly matching).

I can create a pull request if you like.

**Comment by daddyz** [comment]
@rschaden Will be great, just add a test for this case please. Thanks
