### ISSUE TITLE
Possible? Does not seem to work with Finish Numbers

### ISSUE THREAD

**Issue by saelen** [daddyz/phonelib#45]
Example Number.
Country: FI
Phone Number: 030710

possible? returns false but the java / javascript implementation from Google returns true for isPossibleNumber?

https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html

**Comment by saelen** [comment]
Example Code.

require 'phonelib'

Phonelib.default_country = 'FI'
puts Phonelib.possible? '030710'

**Comment by daddyz** [comment]
@saelen Hi, I fixed the issue, can you confirm that it is resolved?

**Comment by saelen** [comment]
Confirmed this is working now with version 0.4.6.  Thank you!  Issue with China also not returning as possible seems to have been resolved as well.
