### ISSUE TITLE
valid_for_country? returns false positives

### ISSUE THREAD

**Issue by pbstriker38** [daddyz/phonelib#49]
```
Loading development environment (Rails 3.2.21)
[1] pry(main)> Phonelib.valid_for_country? '+591 3 3466166', 'DE'
=> true
[2] pry(main)> Phonelib.valid_for_country? '+55 11 2606-1011', 'DE'
=> true
[3] pry(main)> Phonelib.valid_for_country? '+7 926 398-00-95', 'DE'
=> true
[4] pry(main)> Phonelib.valid_for_country? '+55 1 5551234', 'AT'
=> true
[5] pry(main)> Phonelib.valid_for_country? '+57 1 2265858', 'DE'
=> true
```

I'm not sure of the extent of the problem, but a lot of numbers seem to be valid for Germany.

**Comment by daddyz** [comment]
@pbstriker38 It's normal behaviour. You can check with original google's library. 
Keep in mind, that when you are passing country library first of all thinks that you passed national number in case there is no country prefix.
As I see you are passing formatted number with + in the beginning, I will check if I can add some more parsing logic when there is + in number

**Comment by daddyz** [comment]
check against master. It should help you. Now, in case you are passing number that starts with + sign, gem will try to detect country for phone

**Comment by pbstriker38** [comment]
@daddyz Thanks for the update

I was basing my result off of:
![image](https://cloud.githubusercontent.com/assets/5264240/8292324/f332ac0e-18e3-11e5-9e63-59ae6c25fbd9.png)

Is `Result from isValidNumberForRegion(): false` not the same as `valid_for_country?`

**Comment by daddyz** [comment]
My lib is not a total fork of original, the only thing that was forked was a valid and possible methods logic (how they treat regexes and validate against them).
valid_for_country? in my lib will return true in case this number is valid for regex for specified country.
As for isValidNumberForRegion I will find out what that method exactly means and will get back to you.

**Comment by daddyz** [comment]
I looked at the original method, it returns true in case number is valid for region (country) specified. My gem is working in a bit different way. It tries to parse number for specified country, and if it fails, it tries to detect country of the number. When you are using valid_for_country? method, gem is looking into countries where this number was valid and compares the one you passed with array of valid countries.
The difference is that google's library doesn't try to detect (as I remember).

**Comment by pbstriker38** [comment]
I decided to use another method that was better for my application since I have E164 numbers. I parse the number and then get the country.

```
parsed_phone = Phonelib.parse(phone_num)
parsed_phone.country
```

**Comment by daddyz** [comment]
I am currently closing the issue
