### ISSUE TITLE
Not parsing phone numbers from Trinidad & Tobago properly

### ISSUE THREAD

**Issue by adrielfrederick** [daddyz/phonelib#51]
I'm trying to parse some phone numbers from Trinidad & Tobago and a block of them with the +186827xxxxx pattern are not being properly parsed.

To repro:
phone = Phonelib.parse('+18682739106')
phone.country  => "AG"

Trying the same number on http://libphonenumber.appspot.com/phonenumberparser provides the correct result which is "TT"

**Comment by daddyz** [comment]
@adrielfrederick Hi, I updated the data and released new version, now it returns "TT". Please check

**Comment by adrielfrederick** [comment]
Works perfectly. Thanks for the fix!
