### ISSUE TITLE
Canadian mobile numbers detected as fixed_line

### ISSUE THREAD

**Issue by blazeeboy** [daddyz/phonelib#54]
I'm using phonelib 0.4.8, parsing phone numbers and allowing only mobile and fixed_or_mobile types
as our app sends SMS we don't need to allow users to register with a land line, 

When We parse mobile numbers for Canadian operator Tulsa '+1514659xxx2' we get the type as fixed_line and we expected the library to return mobile number, even if there is a doubt a fixed_or_mobile could be allowed.

so am i getting this right and this is a bug or there is something I'm missing in my code?

**Comment by daddyz** [comment]
@blazeeboy Thanks for reporting. I released new version with a fix. 
The issue was that I was returning ```:fixed_or_mobile``` only when patterns match. In case of Canada regexes are different, but both are valid. So I changed gem to return ```:fixed_or_mobile``` when both ```:fixed_line``` and ```:mobile``` are valid.

**Comment by blazeeboy** [comment]
Thank you @daddyz that was fast and perfectly worked, i removed my workaround from my code and it worked like charm.
