### ISSUE TITLE
Add area_code & local_number

### ISSUE THREAD

**Issue by mrsfixit** [daddyz/phonelib#56]
see:
 * https://github.com/sstephenson/global_phone/pull/6
 * https://github.com/GlobalPhone/GlobalPhone/issues/9

**Comment by locochris** [comment]
:+1:

**Comment by daddyz** [comment]
Is it really needed? I guess it's more nice to have feature.
@mrsfixit, thanks for an idea

**Comment by locochris** [comment]
@daddyz - we parse & validate phone numbers, then export them out to external systems.
And quite often the external systems require the phone numbers to be split up in to parts.
eg.
`+61 3 9876 0010` will get exported as:
`<phone_number country_code="61" area_code="3" local_number="9876 0010"/>`

**Comment by mrsfixit** [comment]
@daddyz: @locochris - exactly - we also have this "must have" requirement.

**Comment by daddyz** [comment]
@mrsfixit @locochris released 0.5.0 with this feature
