### ISSUE TITLE
Parsing and using e.164 phone number with extensions

### ISSUE THREAD

**Issue by rosskevin** [daddyz/phonelib#58]
I haven't found much on extensions, but [this writeup on best practices](http://ucken.blogspot.com/2010/12/enterprise-voice-best-practices-in-lync.html) suggests the following e.164 format for phones with extensions:

```
+19052223333;ext=555
```

Unfortunately, here's what I get:

```ruby
phone = Phonelib.parse('+19052223333;ext=555')
phone.valid? # false
phone.e164  # +19052223333555
```

We need to support extensions and would like to store everything in a normalized e.164 format (not separate columns), is there an option to get this to parse properly?

**Comment by rosskevin** [comment]
@daddyz any guidance on parsing and use of phone numbers with extensions?

**Comment by daddyz** [comment]
I started to work on this feature. Want to make it more universal.
Currently the only thing I can suggest is to separate extension before
passing phone to Phonelib

**Comment by daddyz** [comment]
@rosskevin Check master branch. Once you confirm it's ok, I will release new version

**Comment by LaelWatkins** [comment]
Looking forward to this feature!

**Comment by daddyz** [comment]
@rosskevin @LaelWatkins released 0.5.0 with this feature. You can pass extension in the following ways: ```123456789#123```, ```123456789#ext=123```, ```123456789;123```, ```123456789;ext=123```

**Comment by PsychoData** [comment]
just wanted to pass along that some current systems, and most all of the companies I found using extensions in phone numbers used 
`+11234567890x123` or `+1 1234567890 x 123` 
which is to say `+CountryCode PhoneNumberWithAreaCode x ExtensionNumber`

**Comment by daddyz** [comment]
@PsychoData you can use ```Phonelib.extension_separator = 'x'``` in your initializer in order to specify extension separator for the gem. Then it will change the default ";" to "x"
