### ISSUE TITLE
Phonelib.valid?("really1511@now.com") => true

### ISSUE THREAD

**Issue by ghazel** [daddyz/phonelib#59]
```ruby
2.1.5 :001 > Phonelib.valid?("really1511@now.com")
 => true 
```

**Comment by daddyz** [comment]
@ghazel This was parsed like Short Code phone type in US. I made a flag for phonelib to enabled parsing with special phone types or not. You can check it with master. Will be released soon.

**Comment by daddyz** [comment]
@ghazel Released new version with fix
