### ISSUE TITLE
CN = 

### ISSUE THREAD

**Issue by magicalbanana** [daddyz/phonelib#60]
But it should be since 0 is a standard prefix in China's fixed line system.

**Comment by daddyz** [comment]
What is the issue? Can you provide clear explanation?

**Comment by daddyz** [comment]
@magicalbanana If I understood the issue is when trying to parse Chinese national phone with 0 and without you are getting different results like ```2987388888``` and ```02987388888```.
I made a fix and added a test for it. 
Thanks for reporting.
