### ISSUE TITLE
Phonelib.valid?('9111844757') => False, although it is valid number in India.(IN)

### ISSUE THREAD

**Issue by akki91** [daddyz/phonelib#61]

**Comment by daddyz** [comment]
Can you confirm that e164 format of the phone is 919111844757?

**Comment by akki91** [comment]
yes its +919111844757

**Comment by daddyz** [comment]
@akki91 Check with master branch, please

**Comment by daddyz** [comment]
Probably outdated data broke this number validation. Will check and update you soon.

**Comment by daddyz** [comment]
@akki91 Check with master, should be OK

**Comment by daddyz** [comment]
@akki91 Released new version with fix
