### ISSUE TITLE
Norway numbers problem

### ISSUE THREAD

**Issue by LongMan** [daddyz/phonelib#62]
`Phonelib.parse("+47946300000").country` equals `nil`, but it's Norway, and 47 listed in https://github.com/googlei18n/libphonenumber as Norway country code.

**Comment by daddyz** [comment]
@LongMan This number is invalid for Norway. Since number can't be parsed, I can't return country. That's the dependency.
But if you remove one "0" number will be valid, and you will be able to get country.
