### ISSUE TITLE
Clarification for US phone number validations

### ISSUE THREAD

**Issue by andrey-ka** [daddyz/phonelib#63]
We are using phonelib (0.4.9) in our rails project.
Phone number validation is performed using following function call: 

`Phonelib.valid_for_country?([phone_number], [apha2_country_code]).`

Our web site mostly is USA-oriented thus major phone number validations are validated for 'US' country code.
And we are noticed, that phone numbers like with length from 5-9 digits (like 12345, 123456, etc ) are passing validation for US country code.

Here us console raw testing results
`Loading development environment (Rails 3.2.12)`
`2.1.2 :001 > Phonelib.valid_for_country? '12345', 'US'`
` => true `
`2.1.2 :002 > Phonelib.valid_for_country? '123456', 'US'`
 `=> true `
`2.1.2 :003 > Phonelib.valid_for_country? '1234567', 'US'`
` => true
` 

Is it correct behaviour of this library because as far as I know it should be at least 10 digit for USA?
If I'm missing some setting, please correct me.

**Comment by daddyz** [comment]
@andrey-ka Almost sure it's related to short number parsing. Have similar issue.
I made a flag for phonelib to enabled parsing with special phone types or not. You can check it with master. Will be released soon.
This flag is disabled by default in master, so you can try with master branch

**Comment by PaulSchuher** [comment]
@daddyz We've checked that issue on master and it's really fixed, thanks. Could you please let us know in that thread when it released? Thank you so much!

**Comment by daddyz** [comment]
@PaulSchuher @andrey-ka Released new version with this fix

**Comment by andrey-ka** [comment]
@daddyz , many thanks for notification.

**Comment by PaulSchuher** [comment]
@daddyz Thank you so much!
