### ISSUE TITLE
#normalize implementation

### ISSUE THREAD

**Issue by rosskevin** [daddyz/phonelib#64]
Related to extension parsing #58, I would like to have a consistent way to store numbers in the database.  One that hopefully is standard but unlikely to change. 

I was using `#e164`, but with the addition of #58 extensions, the `#e164` doesn't include the extension for storage.

@daddyz are you interested in a `Phonelib.normalize` as a pull request?   This is working for me, renders extensions with the `;`

Something like

```ruby
    def normalize(phone_number)
      phone = ::Phonelib.parse(phone_number)
      value = phone.e164
      value = "#{value};#{phone.extension}" unless phone.extension.blank?
      value
    end
```

**Comment by daddyz** [comment]
@rosskevin I added 2 methods: ```full_e164``` and ```full_international```. They will return phone number with extension.
You can specify 2 settings for extension parsing:
- ```Phonelib.extension_separator``` - sets separator for formatted number for this methods. Default is ";".
- ```Phonelib.extension_separate_symbols``` - sets symbols that separate extension from phone while formatting. Default is ";#".
