### ISSUE TITLE
Phonelib.possible? false negative

### ISSUE THREAD

**Issue by ghazel** [daddyz/phonelib#65]
```
2.1.5 :008 > Phonelib.possible?('(857) 210-0123')
 => false 
```

However:
```
2.1.5 :010 > Phonelib.possible?('(617) 210-0123')
 => true 
```

https://en.wikipedia.org/wiki/Area_codes_617_and_857

**Comment by daddyz** [comment]
@ghazel If you are not specifying country, phonelib will try to detect it from number. So it will fail for 857*** because there is no such country. As for 617*** it will take Australia, and will try to validate phone against this number.
You should specify country or set a default_country for gem.

**Comment by ghazel** [comment]
`possible?()` does not take a country.

**Comment by ghazel** [comment]
That is: https://github.com/daddyz/phonelib/blob/2db045733c71b3beb7a01b4f1ad3c59b7a50fa5d/lib/phonelib/core.rb#L216

**Comment by daddyz** [comment]
Right, it doesn't take, but you can do ```Phonelib.parse(phone, country).possible?``` or set ```Phonelib.default_country = "US"``` in phonelib initializer.
