### ISSUE TITLE
Active Record Integration seems to be buggy

### ISSUE THREAD

**Issue by juliusbachnick** [daddyz/phonelib#66]
When using the active record integration to check whether a provided number is a valid mobile number using 

`validates :phone, uniqueness: true, presence: true, phone: { possible: true, allow_blank: true, types: [ :mobile ] }` and then using a more exotic phone number such as `639297912345` the corresponding record cannot be saved. 

However, if I validate it myself using 

```
validates_uniqueness_of :phone
validate :valid_phone
def valid_phone
    p = Phonelib.parse(self.phone)
    phone_valid = p && p.valid? && p.types.include?(:mobile)
    errors.add(:phone, 'phone number seems to be invalid') if !phone_valid  
  end
```

The record can be saved.

**Comment by daddyz** [comment]
@juliusbachnick Actually it was not buggy, just a bit. 
What was wrong is that you used ```types``` method, which returns all valid types, once you specified ```possible: true``` in validator, it uses ```possible_types``` method. If you were using it, you would mention that you are getting ```:fixed_or_mobile``` as a result. 
Anyway I added a fix, that converts ```:fixed_or_mobile``` into ```:fixed_line``` and ```:mobile```. So it works now.
Thanks for reporting.
