### ISSUE TITLE
This gem is rejected by heroku because it depends on SQLite3

### ISSUE THREAD

**Issue by wandp** [daddyz/phonelib#69]

**Comment by daddyz** [comment]
@wandp How exactly are you deploying to heroku? I added phonelib to my project deployed to heroku there was no problem. Except of this sqlite3 is dependency for development only, there is no dependencies for production.
Please provide some more information

**Comment by wandp** [comment]
could be because its a staging server with some development configurations~
I'll see about changing configs and trying again!
thanks for responding :)

**Comment by daddyz** [comment]
In spec folder there is a dummy rails app used for testing. But if you are
installing gem it should not be included. That rails app has sqlite3 in
it's gemfile. It's the only place I can think about

**Comment by daddyz** [comment]
@wandp Have you solved the issue?
