### ISSUE TITLE
Number Valid checker returns true for alphanumeric string

### ISSUE THREAD

**Issue by prasathsarath** [daddyz/phonelib#70]
Take a local US Number as  a string
and append  and prepend a alphabets to the string
just replace the xxx with a number which you know
For eg:
`num_string = 'asfas+1xxxxxxxxxxfsafsffsafa'`
` Phonelib.valid? num_string`
It returns true
But actually it should return false right?

**Comment by daddyz** [comment]
Not really, it sanitizes the phone number, so it does the validation to the number itself. You can check against ```e164``` method of phone instance for valid number.
But good you asked regarding this, I will add additional configuration parameter that will check for non valid characters and will return false in case they are present

**Comment by daddyz** [comment]
@prasathsarath Hey, I added a ```Phonelib.strict_check``` flag, by default it's ```false```. Set it to ```true``` in initializer in order to get negative validation result for number with alphanumeric string.
Thanks for reporting.

**Comment by prasathsarath** [comment]
@daddyz Cool Thanks
