### ISSUE TITLE
Getting the national number without the country code or formatting

### ISSUE THREAD

**Issue by holgersindbaek** [daddyz/phonelib#71]
I have a phone number, from which I want he unformatted national number, without the country code. This is the phone number:

     2.2.1 :001 > phone = Phonelib.parse('16469129444')
     => #<Phonelib::Phone:0x007fef7814f590 @original="16469129444", @extension="", @sanitized="16469129444", @data={"US"=>{:id=>"US", :country_code=>"1", :international_prefix=>"011", :main_country_for_code=>"true", :national_prefix=>"1", :national_prefix_optional_when_formatting=>"true", :mobile_number_portable_region=>"true", :national=>"6469129444", :format=>{:pattern=>"(\\d{3})(\\d{3})(\\d{4})", :format=>"($1) $2-$3", :intl_format=>"$1-$2-$3"}, :valid=>[:fixed_or_mobile], :possible=>[:premium_rate, :toll_free, :personal_number, :fixed_or_mobile]}}, @national_number="6469129444">

I'm looking to get the '@national_number', but can't since there's no getter for that. Any ideas? Now I do this, which is not optimal:

    phone.e164.sub('+1', '')

**Comment by daddyz** [comment]
@holgersindbaek I added parameter to ```international``` and ```national``` methods. Pass ```false``` to these methods to get unformatted number. Check latest readme.

**Comment by holgersindbaek** [comment]
Perfect, thanks.
