### ISSUE TITLE
International prefix duplicated

### ISSUE THREAD

**Issue by futuretap** [daddyz/phonelib#72]
When I parse these numbers, the international prefix (49) gets duplicated:

```
Phonelib.parse("+49157123456789", "de").international
=> "+49 491 57123456789"

pry(main)> Phonelib.parse("+49157123456789", "de").valid?
=> true

Phonelib.parse("+491521234567", "de").international
=> "+49 491 521234567"

Phonelib.parse("+491521234567", "de").valid?
=> true

```

Both numbers should be invalid (the first subscriber number is too long, the second too short). But they are both detected as valid. IMO, even if the number is invalid, the international prefix shouldn't be duplicated.

**Comment by daddyz** [comment]
@futuretap Sorry for delay. 
You helped to detect another problem, not related to Germany, it's more like libphonenumber's data. They have regex to detect valid number for country, and regexes to detect valid type of phone. They have several countries when valid for country doesn't match, but type's regex does match.
Regarding your problem, Germany, India and Brazil can have country prefix "duplicated" because there are national numbers starting with country prefix. 
You can check with original google's library, it has exactly same behavior.
The fix I made should help you to bypass this problem, now this is what happens:
```ruby
Phonelib.parse("+49157123456789", "de").international # fixed by checking the country regex
 => "+49157123456789" 
Phonelib.parse("+49157123456789", "de").valid? # fixed by checking the country regex
 => false 
Phonelib.parse("+491521234567", "de").international # valid by all regexes, same as original lib does
 => "+49 491 521234567" 
Phonelib.parse("+491521234567", "de").valid? # valid by all regexes, same as original lib does
 => true 
Phonelib.parse("491521234567", "de").international # passed number doesn't have +, don't detect
 => "+491521234567" 
Phonelib.parse("491521234567", "de").valid? # passed number doesn't have +, don't detect
 => false
```
What's happening in last 2 lines, once you pass **+** in the beginning of phone, my library tries to detect country, and does all the validations and checks, in case you don't pass the **+** in the beginning, it will simply check against provided country (if any).
Let me know if you have further questions.

**Comment by futuretap** [comment]
Hm, but this
```
Phonelib.parse("+491521234567", "de").international # valid by all regexes, same as original lib does
 => "+49 491 521234567" 

```

is still wrong. The result should be `"+49 152 1234567". Is this libphonenumber's fault?

**Comment by daddyz** [comment]
Yes, that's what I am saying. Check [here](http://libphonenumber.googlecode.com/svn/trunk/javascript/i18n/phonenumbers/demo-compiled.html)

**Comment by futuretap** [comment]
I tried the phone number `+491521234567` and country code `de` in this tool and it responds with:

```
****Parsing Result:****
{"country_code":49,"national_number":1521234567,"raw_input":"+491521234567","country_code_source":1,"preferred_domestic_carrier_code":""}

****Validation Results:****
Result from isPossibleNumber(): true
Result from isValidNumber(): false
Phone Number region: DE
Result from getNumberType(): UNKNOWN

****Formatting Results:**** 
E164 format: invalid
Original format: +491521234567
National format: 1521234567
International format: invalid
Out-of-country format from US: invalid
Out-of-country format from Switzerland: invalid
```

So this one looks correct because the phone number is indeed invalid.

**Comment by daddyz** [comment]
Try it without + in the beginning. I didn't copy their library, I just used their data. Basically you get same behaviour as I have, just inversed (with and without +)

**Comment by futuretap** [comment]
Why should I try without the + in the beginning? This would mean a different number when dialed. I could replace `+` with `00` since this would actually call the same number. But then I receive the same result as pasted above.

Does this mean you're simply stripping the + in your code?

**Comment by futuretap** [comment]
I think the main problem is that your library considers the number as valid. Interestingly, if I replace `+` with `00` I get the correct result:

```
[9] pry(main)> Phonelib.parse("00491521234567", "de").valid?
=> false # correct
[10] pry(main)> Phonelib.parse("+491521234567", "de").valid?
=> true # not correct
```

**Comment by daddyz** [comment]
I made additional change to lib. Now it should return false result for both numbers - with and without +.
Check against master, if it's ok, I will release another version.

**Comment by futuretap** [comment]
Sorry for the delay. I checked your latest change and it looks good. Fixes the issue. Thanks a lot!

**Comment by bobes** [comment]
@daddyz, I'm not sure if this is the same issue but the german prefix still gets duplicated:
```
Phonelib.parse("+49123456").international
=> "+49 491 23456"
```

**Comment by daddyz** [comment]
@bobes on the latest master 
```
Phonelib.parse("+49123456").international
 => "+49123456"
```
Regarding second example, it tried to detect country
