### ISSUE TITLE
Handling numbers from Puerto Rico

### ISSUE THREAD

**Issue by pedro** [daddyz/phonelib#75]
Hey folks,

I noticed phonelib doesn't seem to treat numbers from Puerto Rico like it does for other US areas.

More specifically it does add a +1 to the `e164` of a valid phone in most US area codes, but not for Puerto Rico's 787:

```
> Phonelib.parse("415 533 1234").e164
=> "+14155332319"

> Phonelib.parse("787 671 1234").e164
=> "+7876711234"
```

Default country is set to "US" in both cases.

Tried updating the data too, but still nothing.

**Comment by pedro** [comment]
Ah, guess the underlying issue here is that it doesn't believe the 787 number is valid.

**Comment by daddyz** [comment]
The number you wrote is invalid for US. 
```ruby
2.1.5 :002 > Phonelib.default_country = :pr
 => :pr 
2.1.5 :003 > Phonelib.parse('7876711234').e164
 => "+17876711234" 
2.1.5 :004 > Phonelib.parse('7876711234').valid?
 => true 
2.1.5 :005 > Phonelib.parse('7876711234', :us).valid?
 => false 
2.1.5 :006 > Phonelib.parse('7876711234', :us).e164
 => "+7876711234"
```
Once it defines, that number is invalid for default country, it tries to detect by phone prefix. I will think of a way of providing several default countries since there are several countries with phone starting with "1".
Currently I added a fix for e164 and international methods, which checks if there is a country code.

**Comment by cachilders** [comment]
> The number you wrote is invalid for US.

Puerto Rico is part of the US, as is the 787 area code. The telephone number @pedro wrote is a valid US number, as :pr == :us. The dataset or the interpretation is buggy; so citing it to disavow the bug/oversight is kind of weird.

**Comment by pedro** [comment]
fwiw I ended up moving to [phony](https://github.com/floere/phony).

phonelib seems more polished and has a better interface imo – but in the end, without knowing much at all about the underlying issue, when I saw phony treated 787 the way I wanted we ended up just moving over.

Will give phonelib another try once multiple default countries are in :+1:!

Thanks folks

**Comment by philihp** [comment]
Wouldn't it be easier just to treat PR as a state?

Is this an issue that should bubble up to Google?

**Comment by neemay11** [comment]
Looks like this is an issue with Google's libphonenumber, rather than phonelib itself

**Comment by allisonphillips** [comment]
Did the digging on this today after a user brought it to our attention that we were rejecting puerto rican phone numbers as invalid... You can add `:pr, :as, :gu, :mp, :vi` to your countries array for US territories (Puerto Rico, American Samoa, Guam, Northern Mariana Islands, US Virgin Islands). Phonelib is requiring a prepended 1 to validate numbers for all of these territories except for Puerto Rico though

**Comment by daddyz** [comment]
@allisonphillips I added an option to define several default countries for parsing, so it suppose to solve the issue, check version 0.7.0
