### ISSUE TITLE
Some Norway phone numbers returned as US

### ISSUE THREAD

**Issue by pduey** [daddyz/phonelib#78]
```
Phonelib.parse("+47 904 48 617").country
=> "NO"
Phonelib.parse("+47 924 48 617").country
=> "US"`
```
Note the 4th number. Works with 0 or 1, but > 1 it returns US.

Testing against libphonenumber directly works as expected:

[https://libphonenumber.appspot.com/phonenumberparser?number=%2B47%20924%2048%20617](https://libphonenumber.appspot.com/phonenumberparser?number=%2B47%20924%2048%20617)

**Comment by pduey** [comment]
I stepped through the code and figured out the problem. I think it's a bug.

My default country is set to US. Since I'm calling parse without the optional country parameter, it attempts to match the number on the default country. If that fails because the number is not valid in that country, then it iterates through all the countries and finds any that match:

- (479) 044-8617 is NOT a valid US number, so it eventually finds Norway.
- (479) 244-8617 IS a valid US number, so it never checks any other countries.

I think that by including the leading '+' sign, i.e., a e164 formatted number, it should not use the default country at all. It should only try the country that matches the e164 formatted number. I'm using two other libraries that integrate with libphonenumber and that's how it's done (e.g., see link above)

If the maintainer agrees, I can do a pull request. Perhaps add it as an option for backwards compatibility.

**Comment by jhealy86** [comment]
Looks like this is related to my issue, #76 . Good to know it's not just me getting bad results with a default country set.

**Comment by daddyz** [comment]
@pduey Check with master please, should be ok now.

**Comment by pduey** [comment]
:thumbsup: :thumbsup: :thumbsup:
