### ISSUE TITLE
Invalid number for Colombia

### ISSUE THREAD

**Issue by cindy8** [daddyz/phonelib#79]
Hi,

I have a case of an invalid number for Colombia `+573234827533`, I'm using the following:

`2.1.1 :008 > number = Phonelib.valid?('+573234827533')
 => false`

The number `+573234827533` is a valid phone number for Claro Colombia, can you please check why the validation fails.

Here is an example of a number that passes the phonelib validation:

`2.1.1 :007 > number = Phonelib.valid?('+573202605272')
 => true`

**Note: I'm using phonelib 0.6.2**

Thanks.

**Comment by daddyz** [comment]
@cindy8 Hi, all the regexes for validation are taken from public resources, Colombian data was taken from [here](https://en.wikipedia.org/wiki/Telephone_numbers_in_Colombia). You can check both numbers with the original [google's library](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) it returns same results.
As written on wiki page:
> 310, 311, 312, 313, 314, 320, 321, 322 Claro formerly known as Comcel

I tried to google a bit regarding 323 prefix without any success.

**Comment by cindy8** [comment]
Hi @daddyz, Thanks for your answer, I also did some research and couldn't find that the code 323 is valid, however our client says it is, I will research some more and let you know if Claro in fact has added the 323 code for their service and request the change on the original google's library and let you know if we need an update 👍 .

Thanks,

**Comment by dmitry** [comment]
For more information check out this one: https://github.com/googlei18n/libphonenumber/blob/master/resources/PhoneNumberMetadata.xml

**Comment by cindy8** [comment]
Thanks @dmitry, I've confirmed with Claro Colombia and the operator `323` is new, I've submit the request to the original google's library, I'll post the update here.

**Comment by cindy8** [comment]
Hi @daddyz, google's libphonenumber included the operator code already 😄, the operator code 323 is valid for Claro Colombia, can you please update the validations?

Thanks

**Comment by cindy8** [comment]
Hi @daddyz when do you think it will be possible to have this change?

**Comment by daddyz** [comment]
@cindy8 I updated data. Check against 0.6.4 version.

**Comment by cindy8** [comment]
It works, thank you @daddyz.
