### ISSUE TITLE
Robustifying input protection

### ISSUE THREAD

**Issue by toxaq** [daddyz/phonelib#81]
Hi, thanks for this gem. I'm just transitioning from the abandoned global_phone gem and one of my tests fails as I was throwing it an intentionally invalid number which happened to be an integer

    Phonelib.parse(123456789)
     NoMethodError: undefined method `split' for 123456789:Fixnum

     Phonelib.parse('123456789')
     => #<Phonelib::Phone:0x007f84e7899360 ....

Might be worth, in the interest of input protection, to convert `original` to a string when passing it to split_extensions? ie in Phonelib::Phone
    
    def initialize(original, country = nil)
      @original, @extension = separate_extension(original.to_s) # Add 'to_s' here

Would submit a pull request but it may not be wanted, as it's not absolutely necessary, and is only a four character change.

**Comment by dmitry** [comment]
@toxaq would be great, but please include tests. :)

**Comment by toxaq** [comment]
Done!
