### ISSUE TITLE
Strict '+' in the beginning 

### ISSUE THREAD

**Issue by Ammet** [daddyz/phonelib#85]
How can I validate Active Record field, to start phone number from `+` ?

Also added validation for some `:phone` attribute:
`441684291707` is `valid`
`+441684291707` is `valid`
`+4416842917076` is `invalid`
`+441684291707x` is `valid`
`+441684291707xxxxxxxxxxxxxxxxxasdasadadas` is `valid`

how can we come to this validation?

Thanks

**Comment by daddyz** [comment]
@Ammet, there is a ```Phonelib.strict_check = true``` option. It will disable passed number sanitizing except for prepending "+". Put it in initializer of your app. You can add another validation for format of the field that will check + in the beginning. So your format validation will check for +, phonelib will check for phone validity.
Tell me if this fits your needs.

**Comment by daddyz** [comment]
@Ammet Is is a suitable solution?

**Comment by rafaltrojanowski** [comment]
Hi, I have similar case:

My code:

```
validates :phone, format: { with: /\+.*/, message: 'must be followed by + character: +66XXXXXXXXX' }, if: lambda { |i| i.phone&.present? }
validates :phone, phone: { allow_blank: true, types: [:mobile] }, if: lambda { |i| i.phone&.present? }
```

It is possible to update record with following phone number:

```
+660841111223random-string-here
```
