### ISSUE TITLE
Getting separated components of an international number

### ISSUE THREAD

**Issue by conorhynesire** [daddyz/phonelib#88]
Is it possible to get the separate components of the international number?

This would be useful for formatting the numbers for use in forms and displays.

Phonelib.parse('0831234567','IE').international
=> "+353 83 123 4567"

Within the code, this is comprised of:

`"+#{country_code} #{national}"`

While we can gain access to country_code trough the accessor method, the national portion of this number is hidden a little bit. The current national method returns the proper formatted number which is correct under the circumstances of the method, but would it be (or is it) possible to get the unformatted national number? IE the "@national_number"

Any help appreciated on this, couldn't see a clear way to do this within the code I can look to add this if necessary.

**Comment by daddyz** [comment]
@conorhynesire I added ```raw_national``` method for returning unformatted national number part of international number

**Comment by conorhynesire** [comment]
completely delayed, but thanks very much appreciate it!
