### ISSUE TITLE
Rails model validator with specific country_code

### ISSUE THREAD

**Issue by matthieupinte** [daddyz/phonelib#92]
Hi,

I would like to use Model validator but with a specific `country_code` to validates phone, and not only the `default_country_code`...
Do I need to create a "custom validator" or we can set the option inline?

Regards ;)

**Comment by daddyz** [comment]
@swibge Like you want to validate your field and to pass country_code to validation? or make it fixed country_code like default country? Provide examples if you can.

**Comment by blainejohnson17** [comment]
Yes, I would also like to same thing..
e.g.
I provide number and country code and the model validator should validate agains't that country code only, not as a default country code.

**Comment by akfernun** [comment]
Would something like this work?

https://github.com/daddyz/phonelib/pull/97

**Comment by akfernun** [comment]
We could probably go ahead and close this thread

**Comment by daddyz** [comment]
@akfernun @blainejohnson17 @matthieupinte released new version
