### ISSUE TITLE
Offline Geocoder returns results without whitespaces

### ISSUE THREAD

**Issue by sashaafm** [daddyz/phonelib#94]
Hello, 

I've recently started exploring Libphonenumber and your lib, specially due to the offline geocoder feature. However, I keep getting the results with the whitespace removed, e.g.:

+351263967870 => VilaFrancadeXira
while the result in the [Appspot Demo](https://libphonenumber.appspot.com/phonenumberparser?number=%2B351263967870) returns the correct name => Vila Franca de Xira

Even more "popular" cities like New Jersey return with the same issue ("NewJersey").

I've experimented this with your most recent gem I believe, in both Ubuntu 16.04 (with Libphonenumber ver. 7.0.7 from `apt-get libphonenumber-dev libgeocoding-dev`) and MacOS Sierra (with Libphonenumber ver. 7.7.2 from `brew install libphonenumber`) and I get the same behaviour.

Is this an issue with your lib or with Libphonenumber itself? Is there a solution?

Thanks!

**Comment by daddyz** [comment]
@sashaafm Hi, thanks for reporting, currently fixed it in master branch only. You can use it.

**Comment by sashaafm** [comment]
Hello @daddyz, thank you for looking into this. I've fetched the master branch like this:

```
source 'https://rubygems.org'

gem 'phonelib', :git => 'git://github.com/daddyz/phonelib.git', :branch => 'master'
```

and upon installing it does say I'm using ver. 0.6.8 of commit master@7c09dab which seems to be the commit where you pushed the fix. However I'm still receiving the results without whitespaces. Am I doing something wrong? 

Thanks, sorry to bother your again

**Comment by sashaafm** [comment]
Hello again @daddyz, I've been trying to find the bug but with no luck so far. Just for a sanity check, it possible it's the file that's already missing the whitespace?

If you could fix this problem soon, I'd be most thankful.

Thank you
