### ISSUE TITLE
.international does not work propery

### ISSUE THREAD

**Issue by holdonnn** [daddyz/phonelib#95]
```
p = Phonlib.parse("+12012064991", "US")
p.international // "+1 201-206-4991"

p = Phonlib.parse("+12012064991", "CA")
p.international // "+12012064991"
```

according to [demo of googlei18n](https://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html)

it should be formatted properly.

**Comment by holdonnn** [comment]
i want international with region "CA"  to be "+1 201-206-4991"

**Comment by daddyz** [comment]
@holdonnn There are several differences between original library and mine, one of them that ```international``` method will return formatted only when number is valid. This number is valid for US but 201 is not a valid canadian NPA prefix. If you won't specify country for ```parse``` method, my library will try to detect valid country.

**Comment by evaneykelen** [comment]
I had to look twice to the GoogleI18N result before I noticed that @holdonnn is indeed right, the number is not a valid US number even according to GoogleI18N.

![image](https://cloud.githubusercontent.com/assets/11846/21962476/65c5031e-db27-11e6-81fc-28cd5b94f9c1.png)

**Comment by holdonnn** [comment]
thanks a lot @daddyz @evaneykelen
